# Generated by Django 4.0.4 on 2022-06-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
